spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/kyuram
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 30MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/seed
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
cors:
  allowed:
    api: /api/**
    url: "http://localhost:3000"
    method: GET, POST, PATCH, DELETE
security:
  patterns:
    ignoring: ["/css/**", "/js/**", "/webjars/**", "/images/**"]
    permit-all: ["/api/members/signup", "/api/members/signin", "/members/signin"]
  jwt:
    issuer: kyuram
    client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
    accessToken:
      header: atoken
      expiry-seconds: 60
    refreshToken:
      header: rtoken
      expiry-seconds: 120